### ISSUE TITLE
TOC breakage

### ISSUE THREAD

**Issue by jimhshen** [J-PAL/admindatahandbook#25]
A new bookdown feature broke the TOC when different chapters have the same title. See: https://github.com/rstudio/bookdown/issues/909

I think the answer is to add "options(bookdown.render.file_scope = FALSE)" _into build.sh above 
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"?

From reading that thread it seems like there's further tweaks to bookdown default behavior to fix this and we'll have to take that option command out at some point too?

**Comment by larsvilhuber** [comment]
In what circumstance did it break it? Describe what is breaking.

There shouldn't be chapters with the same name. There will be sections with the same name, but that shouldn't matter.

You should be able to disambiguate this by having the filenames reflect the sequential numbering of chapters.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
See the build here: https://jimhshen.github.io/admindatahandbook/, go to section 3.1.2. Introduction in the TOC (for the IAB chapter). The link takes you to the top level introduction.

I am putting together the OLDA chapter locally right now (which has yet another introduction section, along with every other section being the same name thanks to following the template, and all of those links in the TOC went to the IAB chapter's sections) and running the "options(bookdown.render.file_scope = FALSE)" fixes it, but I haven't tried committing anything yet.

**Comment by larsvilhuber** [comment]
OK, I read the issue on bookdown github. file scope might work, but careful, as it indicates there might be other breakage. the alternate solution (putting an explicit name to each section) will NOT be implemented here, since it is unmanageable. 

Not sure why they can' t somehow keep track of links as "filename + id"  instead of having some sort of "id"  scheme....

**Comment by jimhshen** [comment]
I tried adding the option into _build.sh but that doesn't seem to fix the issue. The command works locally, where should it go on github?

**Comment by larsvilhuber** [comment]
Of course it doesn't work the way you incorporated it in _build.sh. Each Rscript call is a completely independent R session.

If you test locally, you have to test exactly the same way as on Github. That means running the Rscript commands from the command line.

Three options:

  *   add it to the _setup.R (that gets called after bookdown initializes, but possibly early enough for it to take)
  *   _bookdown.yml  (you'll have to figure out the equivalent YAML syntax)
  *   last alternative: create a "_build.R" script that gets called from _build.sh instead of the individual Rscript calls (i.e., Rscript _build.R)

Try them out in that order.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
